export default {
  colors: {
    primary: "#100F12",
    primaryForeground: "#FFFFFF",
    secondary: "#6B7280",
    secondaryForeground: "#FFFFFF",
    muted: "#F3F4F6",
    mutedForeground: "#6B7280",
    accent: "#E5E7EB",
    accentForeground: "#374151",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D1D5DB",
    input: "#D1D5DB",
    ring: "#100F12",
    background: "#FFFFFF",
    foreground: "#100F12",
    card: "#FFFFFF",
    cardForeground: "#100F12",
    popover: "#FFFFFF",
    popoverForeground: "#100F12",
    text: "#100F12",
  },
  fonts: {
    heading: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    body: "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  },
  radii: {
    base: "0.75rem",
  },
  spacingScale: 1,
};
