import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PageProvider } from "@/lib/page-context";
import Header from "@/components/blocks/header";
import BodyClass from "@/components/ui/body-class";
import Footer from "@/components/blocks/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageProvider>
          <BodyClass />
          <Header />
          {children}
          <Footer />
        </PageProvider>
      </body>
    </html>
  );
}
